export const OUTLINE_PARSING_COPY = {
  parseTitle: "智能大纲解析 (Beta)",
  parseHint: "将外部大纲智能解析为系统格式，支持超长文本（10万字+）的多Agent并行处理。",
  parseInputLabel: "输入内容",
  parseInputPlaceholder: "粘贴大纲文本...",
  parseFileLabel: "或上传文件",
  parseFileAccept: ".txt,.md",
  parseFileHint: "支持 .txt 和 .md 文件",
  parseAdvancedTitle: "高级配置",
  parseContextTokens: "上下文窗口 (tokens)",
  parseTimeout: "超时时间 (秒)",
  parseParallel: "并行提取",
  parseButton: "开始解析",
  parsingButton: "解析中...",
  parseCancelButton: "取消",
  parseResultTitle: "解析结果",
  parseResultOutline: "大纲",
  parseResultCharacters: "角色",
  parseResultEntries: "条目",
  parseApplyAll: "全部应用到项目",
  parseApplyOutline: "保存大纲",
  parseApplyCharacters: "创建角色卡",
  parseApplyEntries: "创建条目",
  parseDone: "解析完成",
  parseFailed: "解析失败",
  agentDashboardTitle: "Agent 执行面板",
  agentStatusPending: "等待中",
  agentStatusRunning: "运行中",
  agentStatusComplete: "已完成",
  agentStatusError: "错误",
  parseApplied: "已应用到项目",
} as const;
