export const AI_GENERATE_DRAWER_COPY = {
  title: "AI 生成",
  close: "关闭",
  llmMissing: "未加载 LLM 配置",
  streamConnecting: "连接中...",
  cancelGenerate: "取消生成",
  autosaveHint: "生成与编辑内容会自动保存（有短暂延迟），也可随时点击“保存”或 Ctrl/Cmd+S 立即保存。",
  basicSection: {
    title: "基础生成",
    instructionLabel: "用户指令",
    targetWordCountLabel: "目标字数（中文按字数=字符数）",
    styleLabel: "风格",
    styleAutoOption: "自动（使用项目默认）",
    systemStylesLabel: "系统预设",
    userStylesLabel: "我的风格",
    styleDefaultPrefix: "项目默认：",
    styleUnset: "（未设置）",
    styleLoadFailedPrefix: " | 加载失败：",
  },
  memorySection: {
    title: "记忆注入",
    previousModeLabel: "前文注入模式",
    previousModeFull: "前文全文",
    previousModeSummary: "前文概要",
    ragLabel: "RAG 检索",
  },
  contextSection: {
    title: "上下文",
    injectionLabel: "上下文注入",
    charactersLabel: "注入角色（可选）",
    charactersEmpty: "暂无角色",
    entriesLabel: "注入条目（可选）",
    entriesEmpty: "暂无条目",
  },
  advancedSection: {
    title: "高级参数",
    collapsedHint: "默认折叠：流式生成。",
    expand: "展开",
    collapse: "收起",
    unsupportedStreamWarning: "不支持流式，生成时会自动回退非流式生成",
    stream: "流式生成（beta）",
  },
  actions: {
    promptInspector: "预检/审查",
    promptInspectorOverrideSuffix: "（覆盖中）",
    resetPromptOverride: "回退默认",
    generate: "生成",
    appendGenerate: "追加生成",
    generating: "生成中...",
    saveAndContinue: "保存并继续",
    save: "保存",
    saving: "保存中...",
  },
} as const;
