export const UI_COPY = {
  common: {
    loading: "加载中...",
    droppedParamsPrefix: "参数已自动降级：",
    copy: "复制",
    requestIdLabel: "请求 ID（request_id）",
  },
  brand: {
    appName: "ainovel Atelier",
  },
  nav: {
    home: "首页",
    groupWorkbench: "项目工作台",
    groupView: "查看",
    groupAiConfig: "项目配置",
    groupAdmin: "管理",

    wizard: "开工向导",
    projectSettings: "项目设置",
    characters: "角色卡",
    entries: "条目",
    outline: "大纲",
    writing: "写作",
    preview: "预览",
    export: "导出",

    search: "搜索引擎",
    styles: "风格",
    prompts: "模型配置",
    promptStudio: "提示词工作室",
    promptTemplates: "提示词模板",
    dataImport: "导入",
    adminUsers: "用户管理",

    navMenu: "导航菜单",
    openNav: "打开导航",
    closeNav: "关闭导航",
    chooseProjectHint: "请选择一个项目以进入编辑页。",
    currentProject: "当前项目",
    backToHome: "返回首页",
  },
  notFound: {
    title: "页面不存在",
    description: "我们找不到你要访问的地址。你可以尝试以下入口：",
  },
  search: {
    title: "搜索引擎",
    subtitle: "VSCode 式全项目搜索（多源聚合，可筛选与跳转；替代旧“术语表/术语映射”入口）",
    queryPlaceholder: "输入关键词…",
    search: "搜索",
    clear: "清空",
    sourcesTitle: "来源",
    sourceLabels: {
      chapter: "章节",
      outline: "大纲",
      character: "角色",
      storyMemory: "剧情记忆",
      sourceDocument: "导入文档",
      entry: "条目",
    },
    emptyHint: "暂无结果",
    loadMore: "加载更多",
    jump: "跳转",
    jumpDisabledHint: "该来源暂不支持跳转",
  },
  vectorRag: {
    title: "向量检索（Vector RAG）",
    subtitle: "Embedding 用于把文本变成向量以便检索；Rerank 用于对候选结果二次排序提升命中（可能增加耗时/成本）。",
    apiKeyHint: "API Key（接口密钥）加密存储，仅回显 masked；留空可使用后端环境变量。",
    save: "保存 RAG 配置",
    dryRunTitle: "测试配置（dry-run）",
    backendEnvFallbackHint: "不确定怎么配时，可保持留空让后端从环境变量读取。",
    pendingClearSuffix: " | 将在保存时清除",
    rerankTitle: "Rerank（重排）",
    rerankConfigDetailsTitle: "Rerank 提供方配置",
    rerankProviderLabel: "Rerank 提供方（provider；项目覆盖；留空=使用后端环境变量）",
    rerankBaseUrlLabel: "Rerank 基础地址（base_url；项目覆盖；留空=使用后端环境变量）",
    rerankModelLabel: "Rerank 模型（model；项目覆盖；留空=使用后端环境变量）",
    rerankTimeoutLabel: "Rerank 超时（timeout_seconds；项目覆盖；留空=使用后端环境变量）",
    rerankHybridAlphaLabel: "Hybrid Alpha（0-1；留空=0）",
    rerankApiKeyLabel: "Rerank API Key（api_key；项目覆盖；留空不修改）",
    rerankClearApiKey: "清除项目级 Rerank API Key",
    rerankResetOverrides: "恢复使用后端环境变量（清除项目覆盖）",
    embeddingTitle: "Embedding（向量化）配置",
    embeddingClearApiKey: "清除项目级 API Key",
  },
  auth: {
    noAccountHint: "没有账号？",
    goRegister: "去注册",
    haveAccountHint: "已有账号？",
    goLogin: "去登录",
    loginTitle: "登录",
    loginSubtitle: "使用本地账号登录（登录状态保存在浏览器 Cookie；数据在服务器数据库）",
    devFallbackHint: "已启用开发演示模式：无需登录也可进入应用。",
    devFallbackRiskHint: "重要：仅用于本地开发/演示。部署到公网时务必关闭 dev_fallback，以免绕过登录。",
    devFallbackNextStepHint: "如需权限/协作/多用户，请在下方使用账号登录。",
    continueInDevFallback: "继续进入应用",
    userIdLabel: "用户名",
    userIdPlaceholder: "例如：admin",
    passwordLabel: "密码",
    passwordPlaceholder: "请输入密码",
    confirmPasswordLabel: "确认密码",
    confirmPasswordPlaceholder: "请再次输入密码",
    passwordHint: "密码至少 8 位",
    reset: "清空",
    login: "登录",
    loggingIn: "登录中...",
    loginSuccess: "登录成功",
    loginFooterHint: "提示：登录状态保存在浏览器 Cookie；退出登录会清理本地登录状态。",
    registerTitle: "注册",
    registerSubtitle: "创建本地账号（账号密码）",
    register: "注册并登录",
    registering: "注册中...",
    registerSuccess: "注册成功",
    logout: "退出登录",
    sessionExpireAtPrefix: "会话到期：",
    devFallbackTag: "本地模式（DEV）",

    linuxdoLogin: "LinuxDo 一键登录/注册",
    linuxdoLoginFailedPrefix: "LinuxDo 登录失败：",
    linuxdoNotEnabledHint:
      "LinuxDo 登录未启用：请在后端环境变量中配置 LINUXDO_OIDC_CLIENT_ID / LINUXDO_OIDC_CLIENT_SECRET / LINUXDO_OIDC_REDIRECT_URI。",
    linuxdoCheckFailedPrefix: "无法检查 LinuxDo 配置：",
  },
  writing: {
    memoryInjectionToggle: "记忆注入",
    memoryInjectionHint: "启用后：生成时会把记忆等模块的结果注入到提示词。",
    memoryInjectionDisabledPreview: "记忆注入已关闭。",
    memoryPackEmpty: "当前为空包（Phase 0 占位）。",
  },
  promptStudio: {
    titleBeta: "提示词工作室（beta）",
    loadingA11y: "正在加载提示词工作室…",
    missingProjectId: "缺少 projectId",
    processing: "处理中…",

    previewNote: "预览通过后端渲染接口生成。",
    backToPrompts: "返回模型配置",
    newbiePromptTemplates: "新手：Prompt 模板",
    goWriting: "去写作",

    intro: "在这里管理预设与提示块，并生成后端渲染预览。",
    recommendedFlow: "推荐流程：模型配置 →（新手模板/工作室）→ 大纲生成 → 章节生成。",
    quickStart: "快速开始：选中预设 → 编辑模板片段 → 右侧预览 → 回到写作页点击“AI 生成”。",
    advancedHint: "提示：这里是高级模式；若你只想改“关键提示词”，建议从“新手：Prompt 模板”开始。",

    conceptTitle: "概念说明（预设/提示块/优先级）",

    enableRecommendedPresets: "一键启用推荐预设（大纲/章节）",

    toastRecommendedNotFound: "未找到推荐预设，请刷新后重试",
    toastRecommendedEnabled: "已启用推荐预设：大纲/章节",
    toastPresetSaved: "已保存预设",
    toastPresetDeleted: "已删除预设",
    toastBlockSaved: "已保存块",
    toastBlockDeleted: "已删除块",
    toastReordered: "已更新排序",

    confirmDeletePresetTitle: "删除预设？",
    confirmDeletePresetConfirm: "删除",
    confirmDeleteBlockTitle: "删除块？",
    confirmDeleteBlockConfirm: "删除",
    confirmDeleteBlockDescFallback: "将删除该提示块。",

    tasks: {
      outlineGenerate: "大纲（outline_generate）",
      chapterGenerate: "章节（chapter_generate）",
      planChapter: "规划（plan_chapter，M3）",
      postEdit: "润色（post_edit，M3）",
      contentOptimize: "正文优化（content_optimize，P0）",
    },
  },
} as const;
